version: "3.8"

services:
  employees:
    container_name: "employees"
    hostname: "employees"
    restart: "always"
    ports:
      - "3000:3000"
    networks:
      - "network"
    build:
      context: "../microservices/employees"
      dockerfile: "application.dockerfile"

  employees_proxy:
    container_name: "employees_proxy"
    hostname: "employees_proxy"
    restart: "always"
    ports:
      - "3001:3001"
    networks:
      - "network"
    build:
      context: "../microservices/employees_proxy"
      dockerfile: "application.dockerfile"

  employees_subscriber:
    container_name: "employees_subscriber"
    hostname: "employees_subscriber"
    restart: "always"
    networks:
      - "network"
    build:
      context: "../microservices/employees_subscriber"
      dockerfile: "subscriber.dockerfile"

  employees_cron:
    container_name: "employees_cron"
    hostname: "employees_cron"
    restart: "always"
    networks:
      - "network"
    build:
      context: "../microservices/employees_cron"
      dockerfile: "cron.dockerfile"

networks:
  network:
    driver: "bridge"